services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: baai-m3-simple-server
    ports:
      - 7003:3000
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
